version: 2.1
executors:
  android-flutter:
    docker:
      - image: gmemstr/flutter-fastlane:latest
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

jobs:
  release:
    executor:
      name: android-flutter
      steps:
        - checkout
        # - run: echo "$PLAY_STORE_UPLOAD_KEY" | base64 --decode > key.jks
        # - run: echo "$PLAY_STORE_UPLOAD_KEY_INFO" | base64 --decode > android/key.properties
        - run: cd android && fastlane release

workflows:
  deploy:
    jobs:
      - release:
          filters:
            branches:
              only: beta
# version: 2.1
# orbs:
#   android: circleci/android@2.2.0

# jobs:
#   build_and_release:
#     executor:
#       name: android/android-machine
#       tag: 2022.12.1
#     parameters:
#       app-name:
#         default: app-online
#         description: app-online|app-internet-home
#         type: string
#       app-env:
#         default: dev
#         description: dev|staging|prod
#         type: string
#     steps:
#       - checkout
#       - run: sudo apt-get update
#       - android/change-java-version:
#           java-version: 17
#       - android/restore-gradle-cache:
#           cache-prefix: v1a
#       - run: chmod +x ./gradlew
#       - run:
#           name: "Build & upload [<< parameters.app-name >>, << parameters.app-env >>] to Firebase AppTester"
#           command: ./gradlew << parameters.app-name >>:assemble<< parameters.app-env >>Release << parameters.app-name >>:appDistributionUpload<< parameters.app-env >>Release
#       - android/save-gradle-cache:
#           cache-prefix: v1a

# workflows:
#   version: 2
#   build_and_release_online:
#     jobs:
#       - build_and_release:
#           filters:
#             tags:
#               only: /^(online)-(v.*)$/
#             branches:
#               ignore: /.*/
#           matrix:
#             parameters:
#               app-name: [ app-online ]
#               app-env: [ dev, staging ]

#   build_and_release_internet_home:
#     jobs:
#       - build_and_release:
#           filters:
#             tags:
#               only: /^(internet-home)-(v.*)$/
#             branches:
#               ignore: /.*/
#           matrix:
#             parameters:
#               app-name: [ app-internet-home ]
#               app-env: [ dev, staging ]
