version: 2.1
executors:
  android-flutter:
    docker:
      - image: gmemstr/flutter-fastlane:latest
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

jobs:
  release:
    executor: android-flutter
    steps:
      - checkout
      - run: gem update --system
      - run: bundle update --bundler
      - run: gem install bundler:2.3.26
      - run: cd android && fastlane release

workflows:
  version: 2
  deploy:
    jobs:
      - release:
          filters:
            tags:
              only: /^(release)$/
            branches:
              only: dev
